services:
  engine:
    container_name: ai-voice-connector-engine
    build:
      context: ../../
      dockerfile: ./docker/Dockerfile
    network_mode: host
    volumes:
      - ./conn:/app/cfg/
    environment:
      CONFIG_FILE: /app/cfg/simple.ini
    env_file:
      - .env

  opensips:
    container_name: ai-voice-connector-opensips
    image: opensips/opensips:latest
    command: -p /etc/opensips/substenv.sh
    volumes:
      - ./b2b:/etc/opensips/
    network_mode: host
    env_file:
      - .env
